# Generated by Django 3.2 on 2021-07-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_farcastuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farcastuser',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='farcastuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='farcastuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='farcastuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='farcastuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='farcastuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='farcastuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='farcastuser',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line'),
        ),
    ]
