# Generated by Django 3.2 on 2021-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210709_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farcastuser',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address'),
        ),
    ]
